create:
	@educates create-cluster 

deploy:
	@educates publish-workshop
	@educates deploy-workshop

serve:
	@educates serve-workshop --patch-workshop

open:
	@educates browse-workshops

destroy:
	@educates delete-cluster --all