apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "workshop"
spec:
  title: "DevopsDays 2025 Workshop"
  description: "Demo Workshop."
  publish:
    image: "$(image_repository)/workshop-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: "$(image_repository)/workshop-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: true
      registry:
        enabled: false
      vcluster:
        enabled: false
    ingresses:
    - name: application
      port: 80
    dashboards:
    - name: App
      url: "$(ingress_protocol)://application-$(session_name).$(ingress_domain)/"
